#spring:
#  datasource:
#    url: jdbc:postgresql://db.kcbuhcsimxedaciaqmcm.supabase.co:5432/postgres
#    username: postgres
#    password: b9gpkG2904h64dGKU2v8
# SPRING_DATASOURCE_URL=jdbc:postgresql://db.kcbuhcsimxedaciaqmcm.supabase.co:5432/postgres?user=postgres&password=b9gpk2904Gh64dGKU2v8

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
    format_sql: true
    highlight_sql: true
logging:
  level:
    org:
      springframework:
        security: debug
      hibernate:
        orm:
          jdbc:
            bind: trace

auth:
  jwt:
    issuer: team.sparta.com
    secret: gH7kRw9FpD3yN2mQxL5aJcUvZ1oP4bS6
    accessTokenExpirationHour: 168