# SPRING_DATASOURCE_URL=jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:6543/postgres?user=postgres.ywwgdmfctgcwcmbyiqds&password=


spring:
  datasource:
    url: jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:6543/postgres
    username : postgres.ywwgdmfctgcwcmbyiqds
    password : UzSLVHyaWUkwpSM6

  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql : true
        use_sql_comments : true
        default_batch_fetch_size : 500
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm :
          jdbc :
            bind : trace
      springframework:
        security : debug

auth:
  jwt:
    issuer: team.sparta.com
    secret: gH7kRw9FpD3yN2mQxL5aJcUvZ1oP4bS6
    accessTokenExpirationHour: 168